{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7315f82f-04a1-4fdd-8871-4c3aecf66a17",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.1 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 701, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 534, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 523, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 429, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 767, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 429, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/39/n8p80q7s1b13_khp67kt_dlw0000gn/T/ipykernel_44825/1852858922.py\", line 1, in <module>\n",
      "    from data_processing import *\n",
      "  File \"/Users/edwardlai/Documents/GitHub/chesslyzer/data_processing.py\", line 179, in <module>\n",
      "    import pandas as pd\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/__init__.py\", line 26, in <module>\n",
      "    from pandas.compat import (\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/compat/__init__.py\", line 27, in <module>\n",
      "    from pandas.compat.pyarrow import (\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/compat/pyarrow.py\", line 8, in <module>\n",
      "    import pyarrow as pa\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.1 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 701, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 534, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 523, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 429, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 767, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 429, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/39/n8p80q7s1b13_khp67kt_dlw0000gn/T/ipykernel_44825/1852858922.py\", line 1, in <module>\n",
      "    from data_processing import *\n",
      "  File \"/Users/edwardlai/Documents/GitHub/chesslyzer/data_processing.py\", line 179, in <module>\n",
      "    import pandas as pd\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/__init__.py\", line 49, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/api.py\", line 9, in <module>\n",
      "    from pandas.core.dtypes.dtypes import (\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/dtypes/dtypes.py\", line 24, in <module>\n",
      "    from pandas._libs import (\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.1 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 701, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 534, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 523, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 429, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 767, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 429, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/39/n8p80q7s1b13_khp67kt_dlw0000gn/T/ipykernel_44825/1852858922.py\", line 1, in <module>\n",
      "    from data_processing import *\n",
      "  File \"/Users/edwardlai/Documents/GitHub/chesslyzer/data_processing.py\", line 179, in <module>\n",
      "    import pandas as pd\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/__init__.py\", line 49, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py\", line 50, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/ops/__init__.py\", line 8, in <module>\n",
      "    from pandas.core.ops.array_ops import (\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/ops/array_ops.py\", line 56, in <module>\n",
      "    from pandas.core.computation import expressions\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/computation/expressions.py\", line 21, in <module>\n",
      "    from pandas.core.computation.check import NUMEXPR_INSTALLED\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/computation/check.py\", line 5, in <module>\n",
      "    ne = import_optional_dependency(\"numexpr\", errors=\"warn\")\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/compat/_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/numexpr/__init__.py\", line 24, in <module>\n",
      "    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.1 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 701, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 534, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 523, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 429, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 767, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 429, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/39/n8p80q7s1b13_khp67kt_dlw0000gn/T/ipykernel_44825/1852858922.py\", line 1, in <module>\n",
      "    from data_processing import *\n",
      "  File \"/Users/edwardlai/Documents/GitHub/chesslyzer/data_processing.py\", line 179, in <module>\n",
      "    import pandas as pd\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/__init__.py\", line 49, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py\", line 64, in <module>\n",
      "    from pandas.core.arrays.masked import BaseMaskedArray\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py\", line 60, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/core/nanops.py\", line 52, in <module>\n",
      "    bn = import_optional_dependency(\"bottleneck\", errors=\"warn\")\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/pandas/compat/_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/Users/edwardlai/anaconda3/lib/python3.11/site-packages/bottleneck/__init__.py\", line 7, in <module>\n",
      "    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    }
   ],
   "source": [
    "from data_processing import *\n",
    "from my_stats import *\n",
    "\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "76175aa4-fa15-4f0b-819d-8a5722c33ace",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Chesslyzer booting...!!!\n",
      "kingside_castles: 2121\n",
      "queenside_castles: 290\n",
      "no_castles: 378\n",
      "total_time_spent: 1481484\n",
      "total_moves: 104084\n",
      "total_win: 1705\n",
      "total_draw: 95\n",
      "total_loss: 984\n",
      "total_checkmated: 399\n",
      "total_timeout: 568\n",
      "total_timevsinsufficient: 42\n",
      "total_resigned: 16\n",
      "total_stalemate: 13\n",
      "total_repetition: 34\n",
      "total_abandoned: 1\n",
      "total_insufficient: 6\n",
      "total_en_passant: 0\n",
      "total_promotions: 375\n",
      "total_games: 2789\n",
      "my_total_flag_wins: 245\n",
      "my_total_flag_losses: 89\n",
      "top_10_flagged_games: [{'link': 'https://www.chess.com/game/live/98402191485', 'opp_time_left': 0.0, 'my_time_left': 1.5, 'my_win_or_lose': 'win', 'my_color': 'black'}, {'link': 'https://www.chess.com/game/live/112181466233', 'opp_time_left': 0.0, 'my_time_left': 4.8, 'my_win_or_lose': 'win', 'my_color': 'black'}, {'link': 'https://www.chess.com/game/live/112342829237', 'opp_time_left': 0.0, 'my_time_left': 1.0, 'my_win_or_lose': 'win', 'my_color': 'black'}, {'link': 'https://www.chess.com/game/live/112420820635', 'opp_time_left': 0.0, 'my_time_left': 4.0, 'my_win_or_lose': 'win', 'my_color': 'white'}, {'link': 'https://www.chess.com/game/live/112421386785', 'opp_time_left': 0.0, 'my_time_left': 1.7, 'my_win_or_lose': 'win', 'my_color': 'white'}, {'link': 'https://www.chess.com/game/live/112422655387', 'opp_time_left': 0.0, 'my_time_left': 3.3, 'my_win_or_lose': 'win', 'my_color': 'black'}, {'link': 'https://www.chess.com/game/live/112423199551', 'opp_time_left': 0.0, 'my_time_left': 4.6, 'my_win_or_lose': 'win', 'my_color': 'black'}, {'link': 'https://www.chess.com/game/live/112423235171', 'opp_time_left': 0.0, 'my_time_left': 1.8, 'my_win_or_lose': 'win', 'my_color': 'white'}, {'link': 'https://www.chess.com/game/live/112426786555', 'opp_time_left': 0.0, 'my_time_left': 3.6, 'my_win_or_lose': 'win', 'my_color': 'white'}, {'link': 'https://www.chess.com/game/live/112429810397', 'opp_time_left': 0.0, 'my_time_left': 4.0, 'my_win_or_lose': 'win', 'my_color': 'white'}]\n",
      "top_10_get_flagged_games: [{'link': 'https://www.chess.com/game/live/112609789651', 'opp_time_left': 1.1, 'my_time_left': 0.4, 'my_win_or_lose': 'win', 'my_color': 'white'}, {'link': 'https://www.chess.com/game/live/108715762821', 'opp_time_left': 2.8, 'my_time_left': 0.5, 'my_win_or_lose': 'win', 'my_color': 'white'}, {'link': 'https://www.chess.com/game/live/106464455389', 'opp_time_left': 2.7, 'my_time_left': 0.6, 'my_win_or_lose': 'win', 'my_color': 'black'}, {'link': 'https://www.chess.com/game/live/103443137087', 'opp_time_left': 0.6, 'my_time_left': 0.6, 'my_win_or_lose': 'win', 'my_color': 'white'}, {'link': 'https://www.chess.com/game/live/113880596753', 'opp_time_left': 1.1, 'my_time_left': 0.6, 'my_win_or_lose': 'win', 'my_color': 'white'}, {'link': 'https://www.chess.com/game/live/115888801847', 'opp_time_left': 4.7, 'my_time_left': 0.7, 'my_win_or_lose': 'win', 'my_color': 'black'}, {'link': 'https://www.chess.com/game/live/101206979607', 'opp_time_left': 2.8, 'my_time_left': 0.7, 'my_win_or_lose': 'win', 'my_color': 'black'}, {'link': 'https://www.chess.com/game/live/117617371785', 'opp_time_left': 1.0, 'my_time_left': 0.7, 'my_win_or_lose': 'win', 'my_color': 'white'}, {'link': 'https://www.chess.com/game/live/108640879431', 'opp_time_left': 1.9, 'my_time_left': 0.8, 'my_win_or_lose': 'win', 'my_color': 'white'}, {'link': 'https://www.chess.com/game/live/109316411115', 'opp_time_left': 3.3, 'my_time_left': 0.9, 'my_win_or_lose': 'win', 'my_color': 'black'}]\n",
      "most_played_openings:                         eco  win_rate  Games_Played\n",
      "0   Alapin-Sicilian-Defense  0.602410           249\n",
      "17        Giuoco-Piano-Game  0.638655           238\n",
      "20             Italian-Game  0.672131           183\n",
      "16           French-Defense  0.612360           178\n",
      "19              Indian-Game  0.641176           170\n",
      "win_loss_draw_percentages: {'win_percentage': np.float64(61.13302258874148), 'loss_percentage': np.float64(35.460738615991396), 'draw_percentage': np.float64(3.4062387952671207)}\n",
      "streaks: {'winning_streak': 25, 'losing_streak': 8}\n",
      "quickest_checkmate:             date moves my_rating opp_rating  my_num_moves  \\\n",
      "1530  2024.05.22    []      2205       2255             0   \n",
      "1634  2024.05.31    []      2205        366             0   \n",
      "\n",
      "                                              link  \n",
      "1530  https://www.chess.com/game/live/110091057621  \n",
      "1634  https://www.chess.com/game/live/110854317093  \n",
      "total_time_spent: 411.5233333333333\n",
      "best_game_by_rating:             date                                              moves my_rating  \\\n",
      "1147  2024.04.10  [e4, e5, Bc4, d6, Nf3, Be7, d4, f6, Nh4, Nh6, ...      2209   \n",
      "\n",
      "     opp_rating  my_num_moves                                          link  \n",
      "1147        100            13  https://www.chess.com/game/live/106464412525  \n",
      "most_played_opponent:               Opponent  Games_Played\n",
      "0          Gerberbaby3            72\n",
      "1         MauntainGoat            65\n",
      "2             sepehr91            27\n",
      "3  accidental_genius23            24\n",
      "4           saltyclown            22\n",
      "Index(['url', 'moves', 'date', 'start_time_est', 'end_time_est', 'time_spent',\n",
      "       'link', 'time_control', 'time_class', 'game_type', 'rated', 'tcn',\n",
      "       'uuid', 'initial_setup', 'fen', 'rules', 'white_username',\n",
      "       'white_rating', 'white_result', 'white_metamoves', 'black_username',\n",
      "       'black_rating', 'black_result', 'black_metamoves', 'eco', 'my_username',\n",
      "       'my_rating', 'my_result', 'my_color', 'my_win_or_lose', 'my_metamoves',\n",
      "       'opp_username', 'opp_rating', 'opp_result', 'opp_metamoves',\n",
      "       'my_time_left', 'opp_time_left', 'my_num_moves', 'my_time_left_ratio',\n",
      "       'opp_time_left_ratio', 'my_moves', 'opp_moves', 'my_castling',\n",
      "       'opp_castling', 'en_passant_count', 'promotion_count', 'num_moves',\n",
      "       'rating_diff'],\n",
      "      dtype='object')\n",
      "Execution time: 3.79 seconds\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "import sys\n",
    "\n",
    "pd.set_option('display.max_rows', None)  # No limit on rows\n",
    "def drop_columns(df):\n",
    "    if 'pgn' in df.columns:\n",
    "        df = df.drop(columns=['pgn'])\n",
    "        print(df.columns)\n",
    "    return df\n",
    "    \n",
    "def main(username):\n",
    "    print(\"Chesslyzer booting...!!!\")\n",
    "    \n",
    "    start_time = time.time()\n",
    "    df = fetch_and_process_game_data(username)\n",
    "    cleaned_df = clean_dataframe(df, username)\n",
    "    cleaned_df = cleaned_df[cleaned_df['rules'] == 'chess']\n",
    "\n",
    "    statistics = total_statistics(cleaned_df)\n",
    "    more_statistics = collect_statistics(cleaned_df)\n",
    "    flag_statistics = get_flag_statistics(cleaned_df)\n",
    "\n",
    "    stats_df = pd.DataFrame(statistics, index=[0])\n",
    "    #more_stats_df = pd.DataFrame(more_statistics, index=[0])\n",
    "    #flag_stats_df = pd.DataFrame(flag_statistics, index=[0])\n",
    "    \n",
    "    # Concatenate all dataframes along the columns (axis=1)\n",
    "    #final_stats_df = pd.concat([stats_df, more_stats_df, flag_stats_df], axis=1)\n",
    "    #print(\"Statistics combined into one dataframe:\")\n",
    "    #print(final_stats_df)\n",
    "\n",
    "    \n",
    "    for stat, value in statistics.items():\n",
    "        print(f\"{stat}: {value}\")\n",
    "    for stat, value in flag_statistics.items():\n",
    "        print(f\"{stat}: {value}\")\n",
    "    for stat, value in more_statistics.items():\n",
    "        print(f\"{stat}: {value}\")\n",
    "\n",
    "    final_df = drop_columns(cleaned_df)\n",
    "    final_df.to_csv(f'csv/{username}.csv', index=False)\n",
    "\n",
    "        \n",
    "    testing_df = final_df.copy()\n",
    "    \n",
    "    end_time = time.time()\n",
    "    duration = end_time - start_time\n",
    "    print(f\"Execution time: {duration:.2f} seconds\")\n",
    "\n",
    "# Boilerplate to run main when executed directly (for testing or debugging)\n",
    "if __name__ == \"__main__\":\n",
    "    username = \"joebruin\"\n",
    "    main(username)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3b70bf98-ec3d-480c-8593-ccdf0351b65c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
